config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  root 'static_pages#home'
  get '/signup' => 'users#new',as: :new_signup
  post '/signup' => 'users#create'
  get '/user/index' =>'users#index',as: :new_index
 
  get '/login' =>'sessions#new',as: :new_login
  get '/record' =>'records#new',as: :new_record
  
  

end

app/models/record.rb
class Record < ActiveRecord::Base
end

app/models/session.rb
class Session < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
  @user = User.find(params[:id])
end

def new
  @user = User.new
end
def index
	@user = User.all
end

def create
  @user = User.new(user_params)
   @user.save
   redirect_to new_login_path
    
  end

private

  def user_params
    params.require(:user).permit(:first_name,:last_name,:user_name,:email,:phone_number,:password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Event</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
             <%= link_to "Create new event",new_login_path,
                                   class: "btn btn-lg btn-primary" %>
 <% else %>
   <%= link_to "Sign up!", new_signup_path,
                               class: "btn btn-lg btn-primary" %>

          </ul>
        </nav>
      </div>
    </header>
    <div class="container">

<%= yield %>

</body>
</html>

app/views/records/new.html.erb
<div class="container">
<h2></h2>
<!-- Trigger the modal with a button -->
<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Create new event</button>

<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
  <div class="modal-dialog">
  
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"></h4>
      </div>
      <div class="modal-body">

<div class="row">
<div class="col-md-6 col-md-offset-3">
 <%= form_for :user do |f| %>

   <%= f.label :event_name %>
   <%= f.text_field :event_name %><br><br>

   <%= f.label :place%>
   <%= f.text_field :place %></br></br>

   <%= f.label :date %>
   <%= f.text_field :date %><br><br>
   
   <%= f.label :time%>
   <%= f.text_field :time %><br><br>
  
   <%= f.label :invitees %>
   <%= f.text_field :invitees%><br><br>

   <%= f.label :status %>
   <%= f.text_field :status%><br><br>

 <% end %>
</div>
</div>
</div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
    
  </div>
</div>

</div>

app/views/static_pages/home.html.erb
<!-- <h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p> -->
<nav class="navbar navbar-default header">
<div class="container-fluid">
  <div class="navbar-header">
    <a class="navbar-brand" href="#">
   <%= image_tag("download.jpg") %></a>
  </div>
  </div>

<div class="center jumbotron">
<h1>Event Scheduling App</h1>
<h2>
 A private event hosting app built for scheduling events
 <a href="http://www.theodinproject.com/"></a>.
</h2>
 
   <%= link_to "Login",new_login_path,
                                   class: "btn btn-lg btn-primary" %>
 <% else %>
   <%= link_to "Sign up now!", new_signup_path,
                               class: "btn btn-lg btn-primary" %>

</div>

app/views/users/index.html.erb
<h1></h1>


<table row='2px'>
 <tr>
  <th>first_name</th>
  <th>last_name</th>
  <th>user_name</th>
  <th>email</th>
  <th>phone_number</th>

 </tr>
<% @user.each do |b|%>
<tr>
<td><%= b.first_name%></td>
<td><%= b.last_name%></td>
<td><%= b.user_name%></td>
<td><%= b.email%></td>
<td><%= b.phone_number%></td>
</tr>
<%end%>
</table>

app/views/users/new.html.erb
<div class="container">
<h2></h2>
<!-- Trigger the modal with a button -->
<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">sign up</button>

<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
  <div class="modal-dialog">
  
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"></h4>
      </div>
      <div class="modal-body">
<div class="row">
<div class="col-md-6 col-md-offset-3">
  <%= form_for(:user) do |f| %>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %></br></br>

    <%= f.label :last_name %>
    <%= f.text_field :last_name %></br></br>


    <%= f.label :user_name %>
    <%= f.text_field :user_name %></br></br>


    <%= f.label :email %>
    <%= f.text_field :email %></br></br>

    
    
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %></br></br>


    <%= f.label :password %>
    <%= f.password_field :password %></br></br>


    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation %></br></br>

<%= f.submit %>
    
  <% end %>
</div>
</div>
</div>
</div>
</div>
</div>
</div>